version: "3.9"

services:
  nginxWeb:
    image: nginx:alpine
    container_name: nginxWeb
    hostname: nginx-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf/:/etc/nginx/conf.d/:rw
      - ./docker/LOGS/nginx:/var/log/nginx
    environment:
      TZ: America/Argentina/Buenos_Aires
    links:
      - mariadb
      - redis
      - php-fpm
    restart: always

  php-fpm:
    build:
      args:
        user: ${USERNAME}
        uid: ${USER_UID}
        phpVersion: ${phpVersion}
      context: ./docker/php/
      dockerfile: Dockerfile
    image: php:${phpVersion}-custom
    container_name: phpFPM
    hostname: php-fpm
    ports:
      - "9001:9000"
    volumes:
      - ./:/var/www/html
      - ./docker/LOGS/php_${phpVersion}/xdebug:/var/log/xdebug
      - ./docker/LOGS/php_${phpVersion}/gral:/var/log/php/
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      XDEBUG_CONFIG: "client_host=localhost remote_port=${XDEBUG_PORT}"
    restart: always
    links:
      - mariadb
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mariadb:
    container_name: mariadb
    hostname: mariadb-database
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./docker/mariadb/database:/var/lib/mysql
      - ./docker/mariadb/initdb:/docker-entrypoint-initdb.d
      - ./docker/LOGS/mariadb:/var/log/mysql
    ports:
      - 3306:3306

  redis:
    restart: always
    image: "redis:alpine"
    container_name: redis
    hostname: redis-alpine
    ports:
      - 6379

  adminer:
    build: ./docker/adminer/.
    container_name: adminer
    image: adminer:username
    hostname: adminer-client
    ports:
      - 8080
    links:
      - mariadb
    environment:
      ADMINER_DEFAULT_SYSTEM: "mysql"
      ADMINER_DEFAULT_SERVER: "mariadb"
      ADMINER_DEFAULT_USERNAME: "root"
      ADMINER_DEFAULT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: America/Argentina/Buenos_Aires
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4